import io
from datetime import datetime
from typing import List

from jinja2 import Template

from app.validators import format_datetime

PDF_TEMPLATE = Template("""<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: Arial, sans-serif; }
        table { width: 100%; border-collapse: collapse; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f26822; color: white; }
        .header { margin-bottom: 20px; }
        .summary { margin-bottom: 30px; }
        .footer { margin-top: 40px; font-size: 12px; color: #666; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ fund_label }}</h1>
        <p>Report generated: {{ generated_at }}</p>
    </div>

    <div class="summary">
        <h2>Summary</h2>
        <p><strong>Total Received:</strong> {{ total_xmr }} XMR</p>
        <p><strong>Transactions:</strong> {{ tx_count }}</p>
        <p><strong>Date Range:</strong> {{ date_from }} to {{ date_to }}</p>
    </div>

    <h2>Transactions</h2>
    <table>
        <tr>
            <th>Date</th>
            <th>TXID</th>
            <th>Amount (XMR)</th>
            <th>Confirmations</th>
            <th>Height</th>
        </tr>
        {% for tx in transactions %}
        <tr>
            <td>{{ tx.timestamp }}</td>
            <td>{{ tx.txid }}</td>
            <td>{{ tx.amount_xmr }}</td>
            <td>{{ tx.confirmations }}</td>
            <td>{{ tx.height }}</td>
        </tr>
        {% endfor %}
    </table>

    <div class="footer">
        Generated by XMR View-Only Dashboard - Fund Transparency Suite
    </div>
</body>
</html>
""")


def generate_pdf_report(
    fund_label: str,
    transactions: List[dict],
    total_xmr: str,
    date_from: datetime,
    date_to: datetime,
    datetime_format: str | None = None,
) -> bytes:
    """Generate PDF report from transaction data."""
    from weasyprint import HTML

    now = datetime.now()
    generated_at = (
        format_datetime(now, datetime_format) if datetime_format else now.isoformat()
    )
    date_from_str = (
        format_datetime(date_from, datetime_format)
        if datetime_format
        else date_from.strftime("%Y-%m-%d")
    )
    date_to_str = (
        format_datetime(date_to, datetime_format)
        if datetime_format
        else date_to.strftime("%Y-%m-%d")
    )

    # Format transaction timestamps if a format is provided
    formatted_transactions = []
    for tx in transactions:
        tx_copy = dict(tx)
        if datetime_format and hasattr(tx_copy["timestamp"], "year"):
            tx_copy["timestamp"] = format_datetime(
                tx_copy["timestamp"], datetime_format
            )
        formatted_transactions.append(tx_copy)

    html_content = PDF_TEMPLATE.render(
        fund_label=fund_label,
        generated_at=generated_at,
        total_xmr=total_xmr,
        tx_count=len(transactions),
        date_from=date_from_str,
        date_to=date_to_str,
        transactions=formatted_transactions,
    )

    pdf_file = io.BytesIO()
    HTML(string=html_content).write_pdf(pdf_file)
    pdf_file.seek(0)
    return pdf_file.read()
